### ISSUE TITLE
Gateekeper : direct mode Forced

### ISSUE THREAD

**Issue by SebHonorine** [vsls-contrib/gatekeeper#2]
Hello there,
Is there a possibility to force the Direct mode to be sure we are bullet proof and not be open to the world?
Regards

**Comment by lostintangent** [comment]
I’d hesitate to enforce this policy for all users, since many remote developers wouldn’t be capable of achieving direct connections between each other. That said, I wonder whether this extension could look for an environment variable of a file on disk, and use that as a “marker” to enforce additional policy. Would something like that work for your org?

**Comment by lostintangent** [comment]
@SebHonorine Per the discussion in #5, we're proposing the addition of a new config file that would allow policies to be managed centrally, and deployed to developer's machines via an existing machine management solution. Do you have any thoughts on whether that would work well for your use case?

**Comment by lostintangent** [comment]
This has been resolved in the latest release! If you create a `$HOME/liveshare-policy.json` file, you can set its contents to the following:

```json
{
  "connectionMode": "direct"
}

**Comment by SebHonorine** [comment]
i ve been caught by something else but nice thanks a lot.
